### PR TITLE
fix issue 72

### PR DESCRIPTION
**Pull request by jw3126**

### CODE REVIEW

**Comment by jw3126** [comment]
Closing in favor of https://github.com/JuliaObjects/ConstructionBase.jl/pull/74

**Comment by jw3126** [comment]
Technically yes. In practice, this is only a problem if a method used in `@genrated` gets refined later.

**Comment by rafaqz** [comment]
I think it was just luck that it had no issues before. It's not that accessing the method table won't ever work in `@generated`, it's that it may break at any point, like it just has, because there is no promise that it will work.

We should avoid adding anything like that in future and be very conservative with changes. This package is widely used basic infrastructure now.

**Comment by rafaqz** [comment]
You're arguing from a position of ignorance though, right? That's likely not a good strategy for writing stable code.

I'm arguing that we need to be conservative _because_ I don't fully understand everything the compiler does (and don't care to), and because I know that it changes and is allowed to in this situation because of that lack of guarantee on accessing mutable state - which does include the method table.

What I'm saying is please don't break half the ecosystem again, and I'm worried you are not becoming more cautious even after this has just happened.

**Comment by jw3126** [comment]
> We should avoid adding anything like that in future and be very conservative with changes. This package is widely used basic infrastructure now.

Agreed.

> What I'm saying is please don't break half the ecosystem again, and I'm worried you are not becoming more cautious even after this has just happened.

Yes in retrospect this usage of which was bad. However, this comment seems rather harsh to me. 
* This was on a nightly julia version, these break very often and 99% of julia users won't notice.
* @aplavin implemented the PR with the problematic code, but everybody was free to review it and request changes. 
  At least I thought it was a good idea and approved it.
* @aplavin was also the one to provide a timely fix.

**Comment by rafaqz** [comment]
Honestly, I review here less because I struggle with this attitude.

I don't have time or energy to argue why function are ok but the method table isn't - its a _lot_ of work to understand and convey exactly why that is how things are, and who has time. 

But we still shouldn't access the method table even if we don't 100% understand, because the docs say not too and we clearly don't know any better.

**Comment by jw3126** [comment]
@aplavin see here https://github.com/JuliaLang/julia/pull/48611#issuecomment-1441418118

**Comment by rafaqz** [comment]
I usually only do much simpler things in `@generated` than calling `which`. For example, using `fieldnames` is fixed for the session so its fair game, but `propertynames` is not, so it's riskier because of potential world age problems. Mostly I use `@generated` to build various unrolled functions from fixed type parameters where things are pretty much `@pure`.

This is a fairly vague heuristic that wont hold up in debate unless being conservative under uncertainty is respected as a rationale. 

I have a few dodgy old packages that do bad things with generated, but that is noted in the readme.

**Comment by rafaqz** [comment]
Exactly with `hasmethod`.  vtjnash is allowed to move these things around wherever he likes because of these caveats in the docs. That's the reason we shouldn't use them, we don't need to understand much more than that.

And overwriting `fieldnames` would be seriously frowned on, and will break everything else too. Changing `propertynames` is, in contrast, encouraged.

**Pull request closed without merging**
