### PR TITLE
use a tuple instead of Ref in broadcasts

### PR DESCRIPTION
**Pull request by rafaqz**
Ref is not free

### CODE REVIEW

**Review by jw3126 — APPROVED** [review]
LGTM. In my experience the the compiler optimizes broadcast Ref like this very well. Are you aware of an example where Tuple is acually faster in a broadcast like this? Anyway I like simple stupid Tuple more than relying on optimizer so LGTM.

**Comment by rafaqz** [comment]
Benchmarking something basic was a Ns faster even though the allocation was elided. I don't have the code right now to demonstrate.

And yes keeping it simple is better anyway, this is really low level code.

**Comment by rafaqz** [comment]
I thought performance was not the reason for the Ref recommendation, instead it's because of scalar unwrapping details.

Tuple logically cant be slower than Ref, and Ref needs compiler optimisations to match a Tuple. I don't think this is any huge revelation.

**Comment by rafaqz** [comment]
Also see the original issues for performance concerns.

https://github.com/JuliaLang/julia/issues/18379

The compiler has to actively elide Ref allocations. My suspicion is at times this complexity will stop it seeing other optimisations in a larger context.

That's important here where this small broadcast will often be in the middle of a much more complicated process that needs high performance.

**Comment by rafaqz** [comment]
Here's a very specific reference to the problem:


https://github.com/JuliaLang/julia/issues/18379

**Comment by rafaqz** [comment]
Here's a very specific reference to the problem:


https://github.com/JuliaLang/julia/issues/18379


And here, Ref blocking constant propagation is identified as a key problem. That may be the reason my own benchmarks were slower too:

https://github.com/JuliaLang/julia/issues/39151#issuecomment-757430014

**Pull request merged**
